# Настройки приложения
spring.application.name=telegram-adapter

# Настройки телеграм бота
telegram.bot.token=your-token-here
telegram.bot.username=your-bot-name

# Настройки Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Топики для сообщений
kafka.topic.commands=cat-commands
kafka.topic.events=cat-events 